# Generated by Django 2.2 on 2020-05-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
