# Generated by Django 3.0.3 on 2020-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_firstfloor_secondfloor_thirdfloor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floorNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
